version: '3.4'

services:
    webhookhub:
        image: ${DOCKER_REGISTRY-}webhookhub
        build:
            context: .
            dockerfile: WebHookHub/Dockerfile
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=eiLuJ2j123eiLuj4