version: '3.4'

services:
    dbwebhookhub:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=T3stUs3rPassW0rD2020
        ports:
          - "1433"
    webhookhub:
        image: webhookhub
        restart: on-failure
        build:
            context: .
            dockerfile: WebHookHub/Dockerfile
        depends_on:
            - dbwebhookhub
        ports:
          - "880:80"
          - "8443:443"
        #entrypoint: ["./wait-for-it.sh", "dbwebhookhub:1433", "--timeout=0", "--", "dotnet", "WebHookHub.dll"]
